server:
  port: 18000
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: fescar-storage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fescar_storage?useSSL=false&serverTimezone=UTC
    username: root
    password: itcast
  main:
    allow-bean-definition-overriding: true
#  cloud:
#    alibaba:
#      seata:
#        tx-service-group: my_test_tx_group




