#端口号
server:
  port: 10086
#服务名称
spring:
  application:
    name: ly-registry
#单个eureka的情况
eureka:
  client:
    fetch-registry: false #不用拉取服务
    register-with-eureka: false #不用在eureka中注册自己
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

  #开发阶段使用，上线需删掉
#  server:
#      enable-self-preservation: false # 关闭自我保护
#      eviction-interval-timer-in-ms: 5000 # 每隔5秒进行一次服务列表清理

